name: Build Report Uploader Image
on:
  push:
    branches:
      - master
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    env:
      REPOSITORY: katalonstudio/report-uploader
      IMAGE_TAG: 0.0.7
      IMAGE_NAME: report-uploader
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build with Maven
        run: mvn clean package

      - name : Prepare docker install
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo apt -y install jq

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Prepare
        run: |
          chmod u+x ./build-image/*.sh
          ./build-image/prevent_overwrite_existing_tag.sh $REPOSITORY $IMAGE_TAG

      - name:  Build
        run: |
          chmod u+x ./build-image/*.sh
          ./build-image/clean.sh $REPOSITORY $IMAGE_TAG
          ./build-image/build.sh $IMAGE_NAME

      - uses: azure/docker-login@v1
        with:
          login-server: registry.hub.docker.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to dockerhub
        run: |
          cd $GITHUB_WORKSPACE
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} docker.io
          ./build-image/tag.sh $REPOSITORY $IMAGE_NAME $IMAGE_TAG
          ./build-image/push.sh $REPOSITORY $IMAGE_TAG
          ./build-image/tag.sh $REPOSITORY $IMAGE_NAME latest
          ./build-image/push.sh $REPOSITORY latest

#      - name: Slack Notification
#        uses: rtCamp/action-slack-notify@master
#        env:
#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}