name: Test Report Uploader Action

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.3

      - name: Upload report to TestOps
        uses: ./
        env:
          EMAIL: ${{ secrets.TESTOPS_EMAIL }}
          PASSWORD: ${{ secrets.TESTOPS_PASSWORD }}
          PROJECT_ID: 6600
          TYPE: junit
          REPORT_PATH: ${{ github.workspace }}/junit-report-sample

