name: Test Report Uploader Action

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.3

      - name: Upload report to TestOps
        uses: ./
        with:
          api-key: ${{ secrets.TESTOPS_API_KEY}}
          project-id: 50236
          report-type: junit
          report-path: ${{ github.workspace }}/junit-report-sample
