name: Test Report Uploader Action

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.3

      - name: Upload report to TestOps
        uses: ./
        with:
          api-key: ${{ secrets.TESTOPS_API_KEY }}
          project-id: 6600
          report-type: junit
          report-path: ${{ github.workspace }}/junit-report-sample

      - name: Upload report to TestOps
        uses: ./
        env:
          TESTOPS_PASSWORD: ${{ secrets.TESTOPS_API_KEY }}
          TESTOPS_PROJECT_ID: 6600
          TESTOPS_REPORT_TYPE: junit
          TESTOPS_REPORT_PATH: ${{ github.workspace }}/junit-report-sample

